### ISSUE TITLE
Error in install ImportError: cannot import name 'scanner'

### ISSUE THREAD

**Issue by yimilan** [webarx-security/wpbullet#3]
Have error to install in debian 8, with phyton 3 no import scanner

https://cl.ly/2ccf487c9b6c

**Comment by LukaSikic** [comment]
Hi @yimilan , how did you install/run the program, as a module?

**Comment by gustavi** [comment]
Same issue here, juste follow installation guide on the README.md.

Logs : 

```
python3 wpbullet.py --help
Traceback (most recent call last):
  File "wpbullet.py", line 2, in <module>
    from core import scanner
  File "/home/jonhdoe/wpbullet/core/scanner.py", line 1, in <module>
    from Modules import *
  File "/home/jonhdoe/wpbullet/Modules/__init__.py", line 1, in <module>
    from .SQLInjection import SQLInjection
  File "/home/jonhdoe/wpbullet/Modules/SQLInjection.py", line 1, in <module>
    from core.modules import BaseClass
  File "/home/jonhdoe/wpbullet/core/modules.py", line 3, in <module>
    from core import scanner
ImportError: cannot import name 'scanner'
```

- OS : Debian 8 up to date
- Python : 3.4.2 (from Debian repos)
- pip : 1.5.6-5 (from Debian repos)
- wpBullet : dev branch (https://github.com/webarx-security/wpbullet/tree/6185112f0a298473ca403f198e8ed686a652da2f)
